### ISSUE TITLE
Tag 3.0.4

### ISSUE THREAD

**Issue by sjmulder** [usgpeople/USG.Authorization#5]
Version 3.0.4 is missing a tag and GitHub Release. Can those be added?

    git tag 3.0.4
    git push --tags

Then on GitHub, go to Releases, create a new one, enter tag 3.0.4, possibly add a changelog.

**Comment by reinvanspaendonck** [comment]
Tagged and released 3.0.4

**Comment by sjmulder** [comment]
Sorry to reopen but 3.0.4 isn't on NuGet yet, maybe something is up with the build pipeline?

**Comment by reinvanspaendonck** [comment]
3.0.4 and 3.0.5 are now on NuGet.

**Comment by sjmulder** [comment]
https://www.nuget.org/packages?q=usg.authorization still shows only 3.0.3 for me
